---
title: "Plots"
output:
  html_document:
    theme: paper
---
#

# NYC Restaurant Inspections Result PLOTS

**Context**

The New York City Department of Health and Mental Hygiene (DOHMH) conducts unannounced restaurant inspections on an annual basis in order to check for compliance with policies on food handling, food temperature, personal hygiene of restaurant workers, and vermin control. Regulation violations are each worth a pre-specified number of points, which are totaled at the end of the inspection. Scores are converted into grades, where a lower score earns a higher grade.

**Data Description**

Data on restaurant inspection results are publicly available at NYC Open Data and are updated daily. The specific data used here was retrieved to be used in class assignments (such as this one) for the **BIST p8105** class at the Mailman Achool of Public Health.

More information on data background and access can be found [here](https://p8105.com/dataset_restaurant_inspections.html).

<font size="3">**DATA VISUALIZATION DASHBOARD**</font>

Plots of the data made to answer Problem 2 of Homework 4 can be found [here](dashboard.html).